spring.application.name=showroom
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=administrator
spring.datasource.url=jdbc:mysql://localhost:3306/showroom_db
