spring.application.name=Siniestros
spring.datasource.url=jdbc:mysql://localhost:3306/empresa_seguros_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

#spring.jpa.hibernate.ddl-auto=create-drop
#spring.sql.init.mode=always

