spring.application.name=miniserie

spring.jpa.hibernate.ddl-auto=update

#Connection with mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=123456789
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


#Connection with h2 db

spring.h2.console.enabled=true
spring.datasource.url= jdbc:h2:mem:navin
spring.datasource.username=admin
spring.datasource.password=