spring.application.name=seguros_autos
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:seguros_autos_db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Configuración para la inicialización de la base de datos
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
