spring.application.name=empresa_seguros
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/empresa_seguros_db
spring.datasource.username=root
spring.datasource.password=administrator
