spring.application.name=empresaSeguros
spring.datasource.url=jdbc:mysql://localhost:3306/empresaSeguros_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true