spring.application.name=concesionarioSeguros
spring.datasource.url=jdbc:mysql://localhost:3306/concesionario_seguros?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=meli
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#Habilita la ejecución de scrips de inicialización
spring.sql.init.mode=always
#Asegura el orden de inicialización
spring.jpa.defer-datasource-initialization=true
